name: Weekly PL Simulation

on:
  schedule:
    - cron: '0 7 * * 1'        # 07:00 UTC every Monday
  workflow_dispatch:            # manual “Run workflow” button

jobs:
  run-sim:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Monte-Carlo engine
        run: python src/simulate_season.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: pl-sim-outputs
          path: results/

     
